export default [
  {
    id: 1,
    name: "cost",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.50",
    status: 1,
    alias: "展现数据-总花费",
    style: 1,
    layout: null,
  },
  {
    id: 2,
    name: "show",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "2.25",
    status: 1,
    alias: "展现数据-展示数",
    style: 1,
    layout: null,
  },
  {
    id: 3,
    name: "click",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "3.50",
    status: 1,
    alias: "展现数据-点击数",
    style: 1,
    layout: null,
  },
  {
    id: 4,
    name: "convert",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "4.25",
    status: 1,
    alias: "转化数据-转化数",
    style: 1,
    layout: null,
  },
  {
    id: 5,
    name: "convert_cost",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "5.50",
    status: 1,
    alias: "转化数据-转化成本",
    style: 1,
    layout: null,
  },
  {
    id: 6,
    name: "phone",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "落地页转化数据-点击电话按钮",
    style: 1,
    layout: null,
  },
  {
    id: 7,
    name: "form",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "5.25",
    status: 1,
    alias: "落地页转化数据-表单提交",
    style: 1,
    layout: null,
  },
  {
    id: 8,
    name: "button",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "落地页转化数据-按钮button",
    style: 1,
    layout: null,
  },
  {
    id: 9,
    name: "view",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "落地页转化数据-关键页面浏览",
    style: 1,
    layout: null,
  },
  {
    id: 10,
    name: "consult",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "落地页转化数据-在线咨询",
    style: 1,
    layout: null,
  },
  {
    id: 11,
    name: "wechat",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "落地页转化数据-微信复制",
    style: 1,
    layout: null,
  },
  {
    id: 12,
    name: "total_play",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "视频数据-播放数",
    style: 1,
    layout: null,
  },
  {
    id: 13,
    name: "share",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-分享数",
    style: 1,
    layout: null,
  },
  {
    id: 14,
    name: "comment",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-评论数",
    style: 1,
    layout: null,
  },
  {
    id: 15,
    name: "like",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-点赞数",
    style: 1,
    layout: null,
  },
  {
    id: 16,
    name: "follow",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-新增关注数",
    style: 1,
    layout: null,
  },
  {
    id: 17,
    name: "home_visited",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-主页访问量",
    style: 1,
    layout: null,
  },
  {
    id: 18,
    name: "message_action",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-私信数",
    style: 1,
    layout: null,
  },
  {
    id: 38,
    name: "click_call_dy",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "互动数据-主页内电话拨打点击量",
    style: 1,
    layout: null,
  },
  {
    id: 39,
    name: "clue",
    agent_id: 1,
    update_time: 1656992536,
    multiple: "1.00",
    status: 1,
    alias: "意向客户线索",
    style: 1,
    layout: null,
  },
];
